'use strict';

/**
 * Extracts a clean major version number from a package.json engines.node string.
 * Handles: "20", ">=18.0.0", "^20.0.0", "20.x", "lts/*"
 * Enforces a minimum of Node 20 — Node 16/18 are EOL and many packages
 * now require 20+.
 */
function parseNodeMajor(raw) {
  if (!raw) return '22';
  const match = raw.match(/\d+/);
  const detected = match ? parseInt(match[0], 10) : 22;
  return String(Math.max(detected, 20));
}

/** Native modules that need extra OS packages or a glibc base (not musl Alpine). */
const NATIVE_DEP_PACKAGES = ['sharp', 'bcrypt', 'canvas', 'sqlite3', 'better-sqlite3'];

function listDeps(packageJson = {}) {
  return { ...packageJson.dependencies, ...packageJson.devDependencies };
}

/**
 * @returns {{ hasSharp: boolean, hasCanvas: boolean, needsBookworm: boolean, needsGcc: boolean }}
 */
function analyzeNativeDeps(packageJson = {}) {
  const deps = listDeps(packageJson);
  const hasSharp = Boolean(deps.sharp);
  const hasCanvas = Boolean(deps.canvas);
  const needsBookworm = hasSharp || hasCanvas;
  const needsGcc = Boolean(
    hasCanvas || deps.bcrypt || deps.sqlite3 || deps['better-sqlite3'],
  );
  return { hasSharp, hasCanvas, needsBookworm, needsGcc };
}

function projectNeedsNativeBuildBase(packageJson = {}) {
  const { needsBookworm, needsGcc } = analyzeNativeDeps(packageJson);
  return needsBookworm || needsGcc;
}

/**
 * Debian packages for bookworm-based images.
 * sharp on glibc uses prebuilt npm binaries — do NOT install libvips-dev (pulls ImageMagick).
 */
function bookwormAptPackages(packageJson = {}, step6 = {}) {
  const deps = listDeps(packageJson);
  const hasCanvas = Boolean(deps.canvas);
  const needsNativeCompile = Boolean(
    hasCanvas || deps.bcrypt || deps.sqlite3 || deps['better-sqlite3'],
  );
  const pkgs = [];

  if (needsNativeCompile) {
    pkgs.push('python3', 'make', 'g++');
  }
  if (hasCanvas) {
    pkgs.push(
      'libcairo2-dev',
      'libpango1.0-dev',
      'libjpeg-dev',
      'libgif-dev',
      'librsvg2-dev',
    );
  }
  if (step6.healthcheck) pkgs.push('wget');

  return [...new Set(pkgs)];
}

/** True when Dockerfile.deploy has BuildKit syntax + apt/npm cache mounts (fast publish). */
function dockerfileHasBuildKitCaches(content = '') {
  return content.includes('syntax=docker/dockerfile:1.4')
    && content.includes('--mount=type=cache');
}

/** Legacy two-stage bookworm Dockerfiles ran apt twice and often missed layer cache on publish. */
function dockerfileUsesLegacyBookwormProdStage(content = '') {
  return content.includes('# ---- Production image ----')
    && content.includes('bookworm');
}

/** libvips-dev on Debian pulls hundreds of ImageMagick packages — avoid for sharp prebuilds. */
function dockerfileInstallsLibvipsDev(content = '') {
  return /\blibvips-dev\b/.test(content);
}

const npmInstall = [
  `RUN --mount=type=cache,target=/root/.npm,sharing=locked \\`,
  `    npm config set loglevel warn \\`,
  `    && ([ -f package-lock.json ] && npm ci --omit=dev --no-audit --no-fund \\`,
  `        || npm install --omit=dev --no-audit --no-fund)`,
];

function appendHealthcheckAndCmd(lines, step6) {
  if (step6.healthcheck) {
    lines.push(``);
    lines.push(`HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \\`);
    lines.push(`  CMD wget -qO- http://localhost:3000/ >/dev/null 2>&1 || exit 1`);
  }

  lines.push(``);
  lines.push(`CMD ["node", "index.js"]`);
  return lines;
}

/**
 * Generates Dockerfile.deploy content from the wizard profile config.
 * @param {object} config — the full wizard store snapshot
 * @param {object} [packageJson] — project package.json (for sharp / native deps)
 * @returns {string}
 */
function generateDockerfile(config, packageJson = {}) {
  const step1 = config.step1 || {};
  const step2 = config.step2 || {};
  const step6 = config.step6 || {};

  const nodeVersion = parseNodeMajor(step1.detectedNodeVersion);
  const isArm64 = step2.architecture === 'arm64' || step2.architecture === 'ARM64';
  const { hasSharp, needsBookworm } = analyzeNativeDeps(packageJson);

  const imageVariant = needsBookworm ? 'bookworm-slim' : 'alpine';
  const baseImage = `node:${nodeVersion}-${imageVariant}`;
  const platformFlag = isArm64 ? '--platform=linux/arm64 ' : '';

  const header = [
    `# syntax=docker/dockerfile:1.4`,
    `# Generated by Wappler Deployment Pipeline`,
    `# Profile: ${config.activeProfile || 'default'}`,
    `# DO NOT edit manually — regenerate via the WDP wizard.`,
    needsBookworm
      ? hasSharp && !analyzeNativeDeps(packageJson).hasCanvas
        ? `# Uses ${imageVariant} for sharp (prebuilt binary — no libvips-dev / ImageMagick).`
        : `# Uses ${imageVariant} for native image modules (canvas / sharp).`
      : '',
    `# BuildKit caches apt/npm between deploys (Docker 20.10+; Engine 28/29 supported).`,
    ``,
  ];

  if (needsBookworm) {
    const osPkgs = bookwormAptPackages(packageJson, step6);
    const osSetup = osPkgs.length
      ? [
          `RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\`,
          `    --mount=type=cache,target=/var/lib/apt,sharing=locked \\`,
          `    apt-get update -qq && apt-get install -y -qq ${osPkgs.join(' ')}`,
          ``,
        ]
      : [];

    const lines = appendHealthcheckAndCmd([
      ...header,
      `FROM ${platformFlag}${baseImage}`,
      ``,
      `WORKDIR /app`,
      ``,
      ...osSetup,
      `COPY package*.json ./`,
      ...npmInstall,
      ``,
      `COPY . .`,
      ``,
      `# Uploads volume mount point`,
      `RUN mkdir -p /app/uploads`,
      ``,
      `EXPOSE 3000`,
    ], step6);

    return lines.filter((line, i, arr) => !(line === '' && arr[i - 1] === '')).join('\n');
  }

  const { needsGcc } = analyzeNativeDeps(packageJson);
  const builderSetup = needsGcc
    ? [`RUN apk add --no-cache python3 make g++`]
    : [];

  const prodOsSetup = step6.healthcheck
    ? [`RUN apk add --no-cache wget`, ``]
    : [];

  const lines = appendHealthcheckAndCmd([
    ...header,
    `FROM ${platformFlag}${baseImage} AS builder`,
    ``,
    `WORKDIR /app`,
    ...builderSetup,
    ...(builderSetup.length ? [''] : []),
    `COPY package*.json ./`,
    ...npmInstall,
    ``,
    `COPY . .`,
    ``,
    `# ---- Production image ----`,
    `FROM ${platformFlag}${baseImage}`,
    ``,
    `WORKDIR /app`,
    ``,
    ...prodOsSetup,
    `COPY --from=builder /app/node_modules ./node_modules`,
    `COPY --from=builder /app .`,
    ``,
    `# Uploads volume mount point`,
    `RUN mkdir -p /app/uploads`,
    ``,
    `EXPOSE 3000`,
  ], step6);

  return lines.filter((line, i, arr) => !(line === '' && arr[i - 1] === '')).join('\n');
}

module.exports = {
  generateDockerfile,
  projectNeedsNativeBuildBase,
  analyzeNativeDeps,
  bookwormAptPackages,
  dockerfileHasBuildKitCaches,
  dockerfileUsesLegacyBookwormProdStage,
  dockerfileInstallsLibvipsDev,
  NATIVE_DEP_PACKAGES,
};
