'use strict';

const { formatEnvValue } = require('../envDeployFormat');
const { normalizeStep3 } = require('../dbDeploy');
const {
  getRedisConnection,
  buildRedisUrl,
  shouldDeployRedisContainer,
} = require('../redisDeploy');

/**
 * Generates .env.deploy content from the wizard profile config.
 * This file holds all secrets and environment-specific values.
 * It must NEVER be committed to version control.
 * @param {object} config — the full wizard store snapshot
 * @returns {string}
 */
function generateEnv(config) {
  const step1  = config.step1  || {};
  const step3  = normalizeStep3(config.step3);
  const step4  = config.step4  || {};
  const step5  = config.step5  || {};
  const step7  = config.step7  || {};
  const addons = step5.addons  || {};
  const profile = config.activeProfile || 'default';

  const lines = [
    `# Generated by Wappler Deployment Pipeline`,
    `# Profile: ${profile}`,
    `# WARNING: This file contains secrets. DO NOT commit to version control.`,
    `#          It is listed in .gitignore automatically by WDP.`,
    ``,
    `# ── Application ──────────────────────────────────────────────────────────`,
    `NODE_ENV=production`,
    `PORT=3000`,
    `SESSION_SECRET=CHANGE_ME_$(openssl rand -hex 32)`,
    ``,
  ];

  // Database
  if (!step3.skipDb) {
    lines.push(`# ── Database ─────────────────────────────────────────────────────────────`);

    if (step3.dbType === 'sqlite') {
      lines.push(`DB_PATH=/app/data/db.sqlite`);
    } else {
      const host = step3.dbLocation === 'managed' ? 'db' : step3.dbHost;
      const port = step3.dbPort || (step3.dbType === 'mysql' ? '3306' : '5432');

      lines.push(`DB_HOST=${host}`);
      lines.push(`DB_PORT=${port}`);
      lines.push(`DB_NAME=${step3.dbName || 'myapp_' + profile}`);
      lines.push(`DB_USER=${step3.dbUser || 'dbuser'}`);
      lines.push(`DB_PASSWORD=${formatEnvValue(step3.dbPassword || 'CHANGE_ME')}`);

      if (step3.dbType === 'mysql') {
        lines.push(`DB_ROOT_PASSWORD=CHANGE_ME_ROOT`);
      }

      // SSL
      if (step3.sslMode && step3.sslMode !== 'disable') {
        lines.push(``);
        lines.push(`# Database SSL/TLS`);
        if (step3.dbType === 'postgres') {
          lines.push(`PGSSLMODE=${step3.sslMode}`);
          if (step3.sslCaPath)   lines.push(`PGSSLROOTCERT=/certs/ca.crt`);
          if (step3.sslCertPath) lines.push(`PGSSLCERT=/certs/client.crt`);
          if (step3.sslKeyPath)  lines.push(`PGSSLKEY=/certs/client.key`);
        } else if (step3.dbType === 'mysql') {
          lines.push(`MYSQL_SSL_MODE=${step3.sslMode.toUpperCase()}`);
          if (step3.sslCaPath)   lines.push(`MYSQL_SSL_CA=/certs/ca.crt`);
          if (step3.sslCertPath) lines.push(`MYSQL_SSL_CERT=/certs/client.crt`);
          if (step3.sslKeyPath)  lines.push(`MYSQL_SSL_KEY=/certs/client.key`);
        }
      }
    }
    lines.push(``);
  }

  // Hosting target extras — DOMAIN/ACME for remote Traefik routing
  if ((step4.hostingTarget === 'digitalocean' || step4.hostingTarget === 'vps' || step4.hostingTarget === 'railway') && addons.traefik?.enabled) {
    const { isExternalTraefik } = require('../traefikDeploy');
    const { traefikDomainEnvLines } = require('../traefikHosts');
    const includeWww = addons.traefik.includeWww !== false;
    const { lines: domainLines, alternate } = traefikDomainEnvLines(
      addons.traefik.domain || 'your-domain.com',
      includeWww,
    );
    lines.push(`# ── Domain / TLS ─────────────────────────────────────────────────────────`);
    lines.push(...domainLines);
    if (alternate) {
      lines.push(`# Let's Encrypt certificate covers both DOMAIN and TRAEFIK_ALT_HOST (same app).`);
    }
    if (isExternalTraefik(addons.traefik)) {
      lines.push(`# Using existing Traefik on the server — ACME is managed by that instance.`);
    } else {
      lines.push(`ACME_EMAIL=${addons.traefik.acmeEmail || 'admin@your-domain.com'}`);
    }
    lines.push(``);
  }

  // Add-on env vars
  const addonLines = [];

  if (addons.redis?.enabled) {
    const conn = getRedisConnection(addons.redis);
    if (conn) {
      addonLines.push(`# ── Redis ────────────────────────────────────────────────────────────────`);
      if (conn.password) {
        addonLines.push(`REDIS_PASSWORD=${formatEnvValue(conn.password)}`);
      }
      addonLines.push(`REDIS_URL=${buildRedisUrl(conn)}`);
      if (!shouldDeployRedisContainer(addons.redis)) {
        addonLines.push(`# Using ${addons.redis.redisMode || 'external'} Redis — no redis service in this compose stack.`);
      }
      addonLines.push(``);
    }
  }

  if (addons.minio?.enabled) {
    addonLines.push(`# ── MinIO ────────────────────────────────────────────────────────────────`);
    addonLines.push(`MINIO_ROOT_USER=minioadmin`);
    addonLines.push(`MINIO_ROOT_PASSWORD=CHANGE_ME_MINIO`);
    addonLines.push(`MINIO_ENDPOINT=http://minio:9000`);
    addonLines.push(``);
  }

  if (addons.n8n?.enabled) {
    addonLines.push(`# ── n8n ──────────────────────────────────────────────────────────────────`);
    addonLines.push(`N8N_USER=admin`);
    addonLines.push(`N8N_PASSWORD=CHANGE_ME_N8N`);
    addonLines.push(``);
  }

  if (addons.plausible?.enabled) {
    addonLines.push(`# ── Plausible Analytics ──────────────────────────────────────────────────`);
    addonLines.push(`PLAUSIBLE_BASE_URL=https://your-domain.com`);
    addonLines.push(`PLAUSIBLE_SECRET_KEY_BASE=CHANGE_ME_$(openssl rand -hex 64)`);
    addonLines.push(``);
  }

  if (addons.restic?.enabled) {
    addonLines.push(`# ── Restic Backups ───────────────────────────────────────────────────────`);
    addonLines.push(`RESTIC_REPOSITORY=s3:https://s3.amazonaws.com/your-bucket`);
    addonLines.push(`RESTIC_PASSWORD=CHANGE_ME_RESTIC`);
    addonLines.push(`BACKUP_CRON=0 2 * * *`);
    addonLines.push(``);
  }

  if (addonLines.length) {
    lines.push(...addonLines);
  }

  // Scanner note
  if (step7.scanners && step7.scanners.length > 0) {
    lines.push(`# ── Security scanners configured ─────────────────────────────────────────`);
    lines.push(`# wdp:scanners=${step7.scanners.join(',')}`);
    lines.push(`# Scanners will run automatically before deployment (Phase 4 feature).`);
  }

  return lines.join('\n');
}

module.exports = { generateEnv };
